;;polymode
(require 'polymode)
(require 'poly-org)

;;cnfonts
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-DAMA-Ubuntu Mono-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 15))

(dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font (frame-parameter nil 'font)
                      charset (font-spec :family "Source Han Serif SC"
                                         :size 15)))
;;lpy
(use-package lpy
  :quelpa (lpy :fetcher github :repo "abo-abo/lpy")
  :ensure t
  :config
  (add-hook 'python-mode-hook #'lpy-mode))

;;awesome-tab
(use-package awesome-tab
  :quelpa (awesome-tab :fetcher github :repo "manateelazycat/awesome-tab")
  :ensure t
  :config
  (awesome-tab-mode 1)
  )

;;aweshell
(use-package aweshell
  :quelpa (aweshell :fetcher github :repo "manateelazycat/aweshell")
  :ensure t
  )

;;org table 对齐
(use-package valign
  :quelpa (valign :fetcher github :repo "casouri/valign")
  :ensure t
  :config
  (add-hook 'org-mode-hook #'valign-mode))

;;lpy
(use-package lpy
  :quelpa (lpy :fetcher github :repo "abo-abo/lpy")
  :ensure t
  :config
  (add-hook 'python-mode-hook #'lpy-mode))

;;multiple-cursor
(require 'multiple-cursors)
(global-set-key (kbd "M-j") 'mc/mark-next-like-this)
(global-set-key (kbd "M-k") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)

;;meow
(use-package meow
  :quelpa (meow :fetcher github :repo "DogLooksGood/meow")
  :ensure t
  :config
  )

;;plain-org-wiki
(use-package plain-org-wiki
  :quelpa (plain-org-wiki :fetcher github :repo "abo-abo/plain-org-wiki")
  :ensure t
  :config
  (setq plain-org-wiki-directory "/home/tonylu/Nutstore Files/我的坚果云/github/wiki")
 )

;;smex
(use-package smex
  :quelpa (smex :fetcher github :repo "nonsequitur/smex")
  :ensure t
  )

;;org-roam
(use-package org-roam
  :quelpa (org-roam :fetcher github :repo "org-roam/org-roam")
  :ensure t
  )

;;stright
;(use-package straight.el
;  :quelpa (straight.el :fetcher github :repo "raxod502/straight.el")
;  :ensure t
;  )

;;wucuo
(use-package wucuo
  :quelpa (wucuo :fetcher github :repo "redguardtoo/wucuo")
  :ensure t
  )
