;; Outline mode for R
(require 'company)
(require 'lazy-load)
(setq tab-always-indent 'complete)
(setq company-idle-delay 0.1)
(global-company-mode)
;; (ess-toggle-underscore nil)
(with-eval-after-load 'ess
  (setq ess-use-company t))

(add-hook 'ess-mode-hook
          '(lambda ()
             (outline-minor-mode)
             (setq outline-regexp "^#.*----")
             (defun outline-level ()
               (cond (looking-at "^#.*----") 1)
               (t 1000)
               )

             (defun send-section-to-R ()
               (interactive ())
               (let ((beg))
                 (if (outline-on-heading-p)
                     (beginning-of-line)
                   (outline-previous-visible-heading 1))
                 (setq beg (point))
                 (set-mark (point))
                 (outline-next-visible-heading 1)
                 (previous-line 1)
                 (end-of-line 1)
                 (ess-eval-region-or-function-or-paragraph-and-step)
                 )
               )
             (local-set-key (kbd "C-c h") 'outline-hide-body)
             (local-set-key (kbd "C-c s") 'outline-show-all)
             (local-set-key (kbd "C-c <left>") 'outline-hide-entry)
             (local-set-key (kbd "C-c <right>") 'outline-show-entry)
             (local-set-key (kbd "C-c <up>") 'outline-previous-heading)
             (local-set-key (kbd "C-c <down>") 'outline-next-heading)
             (local-set-key (kbd "C-c t") 'send-section-to-R)
             )
          )


(provide 'init-ess)
